### ISSUE TITLE
Figs & tables should not include section numbers if number_sections is disabled

### ISSUE THREAD

**Issue by bearloga** [hebrewseniorlife/memor#1]
Hiya! Excellent work here with the template and settings!

My only issue is that if you set `number_sections: no` to remove the section numbers, they're still present in figure and table captions.

I'll be uploading a PR to address this, which you're welcome to reject but I think it makes the final output look better if you don't care about numbered sections.

**Comment by haozhu233** [comment]
Awesome! Thank you!

**Comment by balthasars** [comment]
This only almost fixed the bug, `numbersections = TRUE` is working at the moment, but not `number_sections = TRUE` :)  I'll do a PR.

**Comment by haozhu233** [comment]
Hi, @balthasars, thanks for contributing the PR! The only concern that I have is that it may break other people's existing code while this issue itself is a bit trivial. @bearloga what do you think?

If this is an issue, we could add an ifelse so both `numbersections` and `number_sections` will work. You can check https://pandoc.org/MANUAL.html#conditionals for details.
