### ISSUE TITLE
New Pandoc compains about `cslreferences`

### ISSUE THREAD

**Issue by bearloga** [hebrewseniorlife/memor#8]
The issue (see https://github.com/bearloga/wmf-product-analytics-report/issues/3) _doesn't_ directly affect {memor} (I've checked). However, if using citation styling in any {memor}-based documents (e.g. https://github.com/bearloga/wmf-product-analytics-report/blob/master/R/pdf.R#L76), that creates problems for recent versions of Pandoc.

The underlying issue is a section that is missing from the TeX template (see https://github.com/mpark/wg21/issues/54#issuecomment-569867462 for more info).

I've forked {memor} and added the missing CSL section there (https://github.com/bearloga/memor/commit/6dd1faaf97eb4df6b64aed1597218a706360c6e0) and that fixed it for my {memor}-based template. I wasn't sure whether to submit a PR since this is a fix for an issue of a derivative package. Please let me know if that would be okay.

**Comment by timothytsai** [comment]
This is probably a good idea, especially if a recent version of pandoc is installed.  Are you able to elaborate on why this doesn't directly affect {memor}?  Thanks.

**Comment by bearloga** [comment]
I just did some additional testing and found that it does affect {memor} but only when using a bibliography.

This is the version of Pandoc (installed with Homebrew) I'm using:

```
> rmarkdown::pandoc_version()
[1] ‘2.9.2.1’
```

This is a basic R Markdown doc using {memor}:

```Rmd
---
title: "Title"
author: 
- Your Name
- Second Author
date: "`r Sys.Date()`"
output:
  memor::pdf_memo:
    use_profile: false
---

# Intro

Uses {memor} [@R-memor] template for R Markdown [@R-rmarkdown].

# References
```

All good (using Knit in RStudio IDE but `R -e "rmarkdown::render('Untitled.Rmd')"` would also work):

```
/usr/local/bin/pandoc +RTS -K512m -RTS Untitled.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output Untitled.tex --self-contained --template /Users/mpopov/Library/R/3.6/library/memor/rmarkdown/templates/memor/resources/memor.tex --number-sections --highlight-style tango --pdf-engine xelatex --lua-filter /Users/mpopov/Library/R/3.6/library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /Users/mpopov/Library/R/3.6/library/rmarkdown/rmd/lua/latex-div.lua --variable footer_on_first_page=yes --variable fancy_captions=yes 
output file: Untitled.knit.md


Output created: Untitled.pdf
```

Since there's no bibliography yet, `[@R-memor]` stays like that and doesn't get converted to an actual citation. Now, let's add generate a bibtex file:

```R
knitr::write_bib(c("memor", "rmarkdown"), file = "bibliography.bib")
```

And change the header to:

```YAML
title: "Title"
author: 
- Your Name
- Second Author
date: "`r Sys.Date()`"
output:
  memor::pdf_memo:
    use_profile: false
bibliography: bibliography.bib
```

This is when we encounter a problem:

```
/usr/local/bin/pandoc +RTS -K512m -RTS Untitled.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output Untitled.tex --self-contained --template /Users/mpopov/Library/R/3.6/library/memor/rmarkdown/templates/memor/resources/memor.tex --number-sections --highlight-style tango --pdf-engine xelatex --lua-filter /Users/mpopov/Library/R/3.6/library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /Users/mpopov/Library/R/3.6/library/rmarkdown/rmd/lua/latex-div.lua --variable footer_on_first_page=yes --variable fancy_captions=yes --filter /usr/local/bin/pandoc-citeproc 
output file: Untitled.knit.md

! LaTeX Error: Environment cslreferences undefined.

Error: LaTeX failed to compile Untitled.tex.
```
